version: "3.9"
services:
  redis:
    container_name: redis
    image: redis:6.2.6
    ports:
      - "6379:6379"

  store_upload:
    container_name: store_upload
    image: store_upload:latest
    build:
      context: ./store_upload
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_DB=2
      - OPT_STORES_PER_UPDATE=300
      - OPT_SLEEP_SECONDS=0.1
      - LOGLEVEL=INFO

  tlu:
    container_name: tlu
    image: tlu:latest
    build:
      context: ./tlu
    depends_on:
      - redis
      - store_upload
    environment:
      - REDIS_HOST=redis
      - REDIS_DB=2
      - LOGLEVEL=INFO
      - OPT_MISSING_THRESHOLD=150
